---
resources:
  - name: resource-scripts
    type: git
    source:
        uri: https://github.com/rixycf/concourse-weblog-test.git
        branch: master
  # - name: resource-mds
  #   type: git
  #   source: ((git-mds-repository))

  - name: resource-hugo
    type: git
    source:
        # uri: https://github.com/rixycf/weblog_hugo.git
        branch: master
        uri: ((git-hugo-repository))
        branch: master
        private_key: ((git-ssh-key))
        # submoduleをcloneしてくるようの設定
        submodules: all

  - name: gh-pages
    type: git 
    source:
        branch: master
        uri: ((git-ghpage-repository))
        private_key: ((git-ssh-key))

jobs:
  - name: job-generate-file
    public: false
    plan:
      - get: resource-scripts
        resource: resource-scripts
        trigger: true
      - get: resource-hugo

      - task: generate-file
        config:
            platform: linux
            image_resource:
                type: docker-image
                source:
                    repository: rixycf/hugo_git_alpine
                    tag: 0.1
            inputs:
              - name: resource-scripts
              - name: resource-hugo
            outputs:
              - name: public_modified
            run:
                path: ./resource-scripts/scripts/hugo_generate.sh

      - put: gh-pages
        params:
            repository: public_modified
      # - put: resource-hugo
      #   params: {repositoriy: }
