---
resources:
  - name: resource-scripts
    type: git
    source:
        uri: https://github.com/rixycf/concourse-weblog-test.git
        branch: master
  # - name: resource-mds
  #   type: git
  #   source: ((git-mds-repository))

  - name: resource-hugo
    type: git
    source:
        uri: https://github.com/rixycf/weblog_hugo.git
        branch: master
        # uri: ((git-hugo-repository))
        # branch: master
        # private_key: ((git-ssh-key))

jobs:
  - name: job-generate-file
    public: true
    plan:
      - get: resource-scripts
        resource: resource-scripts
        trigger: true
      - get: resource-hugo

      - task: generate-file
        config:
            platform: linux
            image_resource:
                type: docker-image
                source: {repository: rixycf/hugo_git_alpine}
            inputs:
              - name: resource-scripts
              - name: resource-hugo
            run:
                path: ./resource-scripts/scripts/hugo_generate.sh
      # - put: resource-hugo
      #   params: {repositoriy: }
